- name: Infrastructure Services [ZTD server]
  hosts: us-east-dhcp*
  become: true
  collections:
    - nginxinc.nginx_core
  gather_facts: true
  vars:
      netbox_url: "{{ lookup('env', 'NETBOX_API') }}"
      netbox_token: "{{ lookup('env', 'NETBOX_TOKEN') }}"
      ztd_script_root: "http://scriptrepo.yourorg.com/tftp/ztd"
      www_root: /var/www
      ztd_dir: ztd
      ztd_scripts_dir: os10_scripts
      os10_images_dir: images
      post_install_scripts_dir: post_install_scripts
      os10_versions:
        - version: dell_os10_10.5.1.0
          binary: PKGS_OS10-Enterprise-10.5.1.0.124stretch-installer-x86_64.bin
        - version: dell_os10_10.5.2.0 
          binary: PKGS_OS10-Enterprise-10.5.2.0.232stretch-installer-x86_64.bin
        - version: dell_os10_10.5.2.2
          binary: PKGS_OS10-Enterprise-10.5.2.2.258stretch-installer-x86_64.bin
  tasks:
    - name: "Create File Structure"
      file:
        path: "{{item}}"
        state: directory
        mode: '0755'
      loop:
        - "{{www_root}}"
        - "{{www_root}}/{{ztd_dir}}"
        - "{{www_root}}/{{ztd_dir}}/{{os10_images_dir}}"
        - "{{www_root}}/{{ztd_dir}}/{{ztd_scripts_dir}}"
        - "{{www_root}}/{{ztd_dir}}/{{post_install_scripts_dir}}"
    
    - name: "create os10 script dirs"
      file:
        path: "/var/www/ztd/os10_scripts/{{item.version}}"
        state: directory
        mode: '0755'
      with_items: "{{os10_versions}}"
    
    - name: config | Configuring DHCP Service
      template:
        src: templates/ztd/ztd.sh.j2
        dest: "/var/www/ztd/os10_scripts/{{item.version}}.sh"
        mode: '0755'
      with_items: "{{os10_versions}}"
  roles:
    - role: nginx
  post_tasks:
    - name: "Link www to nginx root"
      file:
        src: "{{www_root}}/ztd"
        dest: /usr/share/nginx/html/ztd
        state: link
