- name: Infrastructure Services [ZTD server]
  hosts: us-east-dhcp*
  become: true
  collections:
    - nginxinc.nginx_core
  gather_facts: true
  vars:
    netbox_url: "{{ lookup('env', 'NETBOX_API') }}"
    netbox_token: "{{ lookup('env', 'NETBOX_TOKEN') }}"
    ztd_server_ip: 172.16.135.2
    www_root: /var/www
    hostmap_file: hostmap.txt
    ztd_dir: ztd
    sonic_dir: sonic
    ztd_scripts_dir: os10_scripts
    os10_images_dir: images
    cli_conf_path: cli_config
    post_install_scripts_dir: post_install_scripts
    sonic_versions:
      - version: sonic
    os10_versions:
      - version: dell_os10_10.5.1.0
        binary: PKGS_OS10-Enterprise-10.5.1.0.124stretch-installer-x86_64.bin
      - version: dell_os10_10.5.2.0
        binary: PKGS_OS10-Enterprise-10.5.2.0.232stretch-installer-x86_64.bin
      - version: dell_os10_10.5.2.2
        binary: PKGS_OS10-Enterprise-10.5.2.2.258stretch-installer-x86_64.bin
    isc_dhcp_name_servers:
      - 8.8.8.8
      - 8.8.4.4
    ntp_server: time.nist.gov
  pre_tasks:
    - name: "get management interfaces from netbox"
      delegate_to: localhost
      set_fact:
        mgmt_interfaces: "{{ query('netbox.netbox.nb_lookup', 'interfaces',
          api_filter='tag=ztd',
          api_endpoint=netbox_url, token=netbox_token) }}"
  tasks:
    - name: "Create File Structure"
      file:
        path: "{{item}}"
        state: directory
        mode: "0755"
      loop:
        - "{{www_root}}"
        - "{{www_root}}/{{ztd_dir}}"
        - "{{www_root}}/{{ztd_dir}}/{{os10_images_dir}}"
        - "{{www_root}}/{{ztd_dir}}/{{ztd_scripts_dir}}"
        - "{{www_root}}/{{ztd_dir}}/{{post_install_scripts_dir}}"
        - "{{www_root}}/{{ztd_dir}}/{{cli_conf_path}}"
        - "{{www_root}}/{{sonic_dir}}"
        - "{{www_root}}/{{sonic_dir}}/ztp"
        - "{{www_root}}/{{sonic_dir}}/config"
        - "{{www_root}}/{{sonic_dir}}/sonic_scripts"

    - name: config | Configuring ZTD Scripts
      template:
        src: templates/ztd/ztd.sh.j2
        dest: "/var/www/ztd/os10_scripts/{{item.version}}.sh"
        mode: "0755"
      with_items: "{{os10_versions}}"

    - name: config | Configuring CLI Config file
      template:
        src: templates/ztd/post_install.sh.j2
        dest: "/var/www/ztd/{{post_install_scripts_dir}}/post_install.sh"
        mode: "0755"

    - name: config | Configuring CLI Config file
      template:
        src: templates/ztd/cli_config.j2
        dest: "/var/www/ztd/{{cli_conf_path}}/cli_config"
        mode: "0755"

    - name: config | Configuring Hostmap file
      template:
        src: templates/ztd/hostmap.txt.j2
        dest: "/var/www/ztd/{{hostmap_file}}"
        mode: "0755"
    - name: write ztp files for sonic
      template:
        src: templates/sonic/ztp.json.j2
        dest: "/var/www/{{sonic_dir}}/ztp/{{ mgmt_interface.value.device.display }}_ztp.json"
        mode: "0755"
      with_items: "{{ mgmt_interfaces }}"
      loop_control:
        loop_var: mgmt_interface
    - name: write ztp configs for sonic
      template:
        src: templates/sonic/config/config_db.json.j2
        dest: "/var/www/{{sonic_dir}}/config/{{ mgmt_interface.value.device.display }}_config_db.json"
        mode: "0755"
      with_items: "{{ mgmt_interfaces }}"
      loop_control:
        loop_var: mgmt_interface
    - name: config | Configuring post install script
      template:
        src: templates/sonic/post_install.sh.j2
        dest: "/var/www/{{sonic_dir}}/sonic_scripts/post_install.sh"
        mode: "0755"
  roles:
    - role: nginx
  post_tasks:
    - name: "Link ztd to nginx root"
      file:
        src: "{{www_root}}/ztd"
        dest: /usr/share/nginx/html/ztd
        state: link
    - name: "Link sonic to nginx root"
      file:
        src: "{{www_root}}/sonic"
        dest: /usr/share/nginx/html/sonic
        state: link
