- name: Infrastructure Services [ZTD server]
  hosts: us-east-dhcp*
  become: true
  collections:
    - nginxinc.nginx_core
  gather_facts: true
  vars:
      netbox_url: "{{ lookup('env', 'NETBOX_API') }}"
      netbox_token: "{{ lookup('env', 'NETBOX_TOKEN') }}"
      ztd_script_root: "http://scriptrepo.yourorg.com/tftp/ztd"
      os10_versions:
       - dell_os10_10.5.1.0
       - dell_os10_10.5.2.0
       - dell_os10_10.5.2.2
  pre_tasks:
    - name: "Create File Structure"
      file:
        path: "{{item}}"
        state: directory
        mode: '0755'
      loop:
        - /var/www
        - /var/www/ztd
        - /var/www/ztd/os10_scripts
        - /var/www/ztd/post_install_scripts
  roles:
    - role: nginx
  post_tasks:
    - name: "Link www to nginx root"
      file:
        src: /var/www/ztd
        dest: /usr/share/nginx/html/ztd
        state: link
