- name: Infrastructure Services [ZTD server]
  hosts: device_roles_leaf
  gather_facts: false

  vars:
    netbox_url: "{{ lookup('env', 'NETBOX_API') }}"
    netbox_token: "{{ lookup('env', 'NETBOX_TOKEN') }}"
  tasks:
  - name: Show version
    shell:
      cmd: "show version | grep Software | awk '{print $NF}'"
    register: version_info
  - name: format variables
    set_fact:
      fmt_version_info: "{{ ((version_info.stdout | lower) | replace('.','-')) }}" #netbox is converting periods to dashes so I need to convert version info into the same format.
      platform: "{{ hostvars[inventory_hostname]['platforms'][0] }}"

  - name: write switch data to audit file
    delegate_to: localhost
    shell:
      cmd: "echo '{{ inventory_hostname }},{{ fmt_version_info }},{{ platform }}' >> /tmp/switch_audit.csv"
