---
- name: write ztp files for sonic
  template:
    src: templates/sonic/ztp.json.j2
    dest: "/var/www/{{sonic_dir}}/ztp/{{ device.value.display }}_ztp.json"
    mode: "0755"
- name: Get mgmt interfaces from NetBox
  uri:
    url: "{{ netbox_url }}/api/dcim/interfaces/?device={{ device.value.name }}&name=mgmt"
    method: GET
    return_content: yes
    headers:
      accept: "application/json"
      Authorization: "Token {{ netbox_token }}"
  register: mgmt_interfaces
- name: write ztp configs for sonic
  template:
    src: templates/sonic/config/config_db.json.j2
    dest: "/var/www/{{sonic_dir}}/config/{{ device.value.display }}_config_db.json"
    mode: "0755"
