---
- name: redhat | Installing DHCP Packages
  yum:
    name: dhcp
    state: present
  become: true
  when: ansible_distribution != "Fedora"

- name: redhat | Ensuring DHCP Service is Enabled
  service:
    name: dhcpd
    enabled: true
  become: true
