- name: "GATHER DATA FROM NETBOX"
  hosts: us-east-dhcp*
  gather_facts: no
  vars:
    netbox_url: "{{ lookup('env', 'NETBOX_API') }}"
    netbox_token: "{{ lookup('env', 'NETBOX_TOKEN') }}"
    ansible_user: gns3
    ansible_pass: gns3
  tasks:
    - name: "GET interface WITH NB_QUERY"
      delegate_to: localhost
      set_fact:
        mgmt_interfaces: "{{ query('netbox.netbox.nb_lookup', 'interfaces', 
                api_filter='tag=ztd',
                api_endpoint=netbox_url, token=netbox_token) }}"
    - name: do something
      debug:
        msg: "blah blah blah {{ item.value.device.display }} {{hostvars[item.value.device.display]['primary_ip4']}}"
      with_items: "{{mgmt_interfaces}}"
    