- name: "GATHER DATA FROM NETBOX"
  hosts: dhcp
  gather_facts: no
  vars:
    netbox_url: "{{ lookup('env', 'NETBOX_API') }}"
    netbox_token: "{{ lookup('env', 'NETBOX_TOKEN') }}"
  tasks:
    - name: "GET interface WITH NB_QUERY"
      delegate_to: localhost
      set_fact:
        mgmt_interfaces: "{{ query('netbox.netbox.nb_lookup', 'interfaces', 
                api_filter='tag=ztd',
                api_endpoint=netbox_url, token=netbox_token) }}"

    - debug:
        msg: "{{ mgmt_interfaces | json_query('[*].value.device') }}"